version: "3.8"
services:
    www:
        build: .
        container_name: 'www'
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        networks:
            - default
networks:
    default:
        driver: bridge
